---
- name: Get FBC image sha
  when: test_env == "stage"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  ansible.builtin.shell: |
    set -o pipefail
    POD_NAME=$(oc -n openshift-marketplace get pods -o name | grep numaresource | head -n 1)
    oc -n openshift-marketplace get "$POD_NAME" -o json | jq -r '.status.containerStatuses[0].imageID'
  changed_when: fbc_image_sha.rc == 0
  register: fbc_image_sha

- name: Save pull secret
  ansible.builtin.copy:
    content: "{{ pull_secret_string | b64decode }}"
    dest: /tmp/pull_secret
    mode: '0660'

- name: Get must gather sha
  ansible.builtin.shell: >
    skopeo inspect
    --authfile /tmp/pull_secret docker://{{ must_gather_image }}
    --format '{% raw %}{{.Digest}}{% endraw %}'
  changed_when: mustgather_image_sha.rc == 0
  register: mustgather_image_sha

# for 4.12 releases use rhel8 base image
- name: Set UBI base image
  ansible.builtin.set_fact:
    base_image: "{% if ocp_version_minor == 12 %}rhel8{% else %}rhel9{% endif %}"
  when: custom_scheduler is not defined

- name: Set scheduler image uri
  ansible.builtin.set_fact:
    scheduler_image_uri: "{{ image_uri[test_env] }}/{{ scheduler_image_name }}-{{ base_image }}:v{{ ocp_version_major }}.{{ ocp_version_minor }}"
  when: custom_scheduler is not defined

- name: Overwrite scheduler image uri
  ansible.builtin.set_fact:
    scheduler_image_uri: "{{ custom_scheduler }}"
  when: custom_scheduler is defined

- name: Get Scheduler image sha
  ansible.builtin.shell: >
    skopeo inspect
    --authfile /tmp/pull_secret  docker://{{ scheduler_image_uri }}
    --format '{% raw %}{{.Digest}}{% endraw %}'
  changed_when: scheduler_image_sha.rc == 0
  register: scheduler_image_sha

- name: Save images sha information
  ansible.builtin.copy:
    dest: "{{ tmp_workdir }}/image-sha.yaml"
    mode: '0664'
    owner: "{{ ansible_user }}"
    content: |
      fbc_image_sha: {{ fbc_image_sha.stdout | default("No SHA on Prod") }}
      "{{ must_gather_image }}": {{ mustgather_image_sha.stdout }}
      "{{ scheduler_image_uri }}": {{ scheduler_image_sha.stdout }}
