---
collections:
  - name: community.libvirt
    version: "1.3.0"
  - name: redhatci.ocp
    version: "2.5.1749150845"
  - name: kubernetes.core
    version: "2.4.2"
  - name: junipernetworks.junos
    version: "9.1.0"
