---
collections:
  - name: community.libvirt
    version: 1.3.0
  - name: redhatci.ocp
    source: https://github.com/mvk/ansible-collection-redhatci-ocp.git
    type: git
    version: mvk-role-test_report_send
  - name: kubernetes.core
    version: 2.4.2
  - name: junipernetworks.junos
    version: 9.1.0
#    version: 89962fa4f89434092c01e583d44f255531acc684
