---
collections:
  - name: community.libvirt
    version: 1.3.0
  - name: redhatci.ocp
    source: https://github.com/mvk/ansible-collection-redhatci-ocp.git
    type: git
    version: role-report-send-p2
  - name: kubernetes.core
    version: 2.4.2
  - name: junipernetworks.junos
    version: 9.1.0
