---
- name: Push CI JUnit XML report data to collector
  hosts: localhost
  vars:
    collection_roles: "collections/ansible_collections/redhatci/ocp/roles"
    target_path: "{{ playbook_dir }}/upload"
    global_json_reports_list: []
  pre_tasks:
    - name: Print CI detection variables' values
      when:
        - rs_debug is defined and rs_debug
      block:
        - name: Print detection variable {{ item }}
          ansible.builtin.debug:
            msg: "{{ item }}: '{{ lookup('env', item, default='unset') }}'"
          loop:
            - DCI_CS_URL
            - GITHUB_API_URL
            - GITLAB_CI
            - JENKINS_URL
            - PROW_JOB_ID
    - name: Initialize rs_collector_url
      ansible.builtin.set_fact:
        rs_collector_url: "{{ rs_collector_url | default('') }}"
    - name: Update rs_collector_url from splunk_url
      ansible.builtin.set_fact:
        rs_collector_url: "{{ splunk_url }}"
      when:
        - rs_collector_url | length == 0
        - splunk_url | default("") | length > 0
    - name: Initialize rs_collector_auth_headers
      ansible.builtin.set_fact:
        rs_collector_auth_headers: "{{ rs_collector_auth_headers | default({}) }}"
    - name: Update rs_collector_auth_headers from splunk_channel
      ansible.builtin.set_fact:
        rs_collector_auth_headers: "{{ rs_collector_auth_headers | combine({'X-Splunk-Request-Channel': splunk_channel}) }}"
      when:
        - splunk_channel | default("") | length > 0
    - name: Initialize rs_collector_auth_token
      ansible.builtin.set_fact:
        rs_collector_auth_token: "{{ rs_collector_auth_token | default('') }}"
    - name: Update rs_collector_auth_token
      ansible.builtin.set_fact:
        rs_collector_auth_token: "{{ splunk_token }}"
      when:
        - rs_collector_auth_token | length == 0
        - splunk_token | default("") | length > 0
    - name: Initialize rs_collector_source
      ansible.builtin.set_fact:
        rs_collector_source: "{{ rs_collector_source | default('') }}"
    - name: Update rs_collector_source from splunk_source
      ansible.builtin.set_fact:
        rs_collector_source: "{{ splunk_source }}"
      when:
        - rs_collector_source | length == 0
        - splunk_source | default("") | length > 0

    - name: Load role redhatci.ocp.test_report_send only for its defaults (not tasks)
      ansible.builtin.import_role:
        name: redhatci.ocp.report_send
        defaults_from: main.yml
        tasks_from: empty.yml
        public: true
    - name: Validate legal rs_ci_system value
      ansible.builtin.assert:
        that:
          - rs_ci_system in rs_ci_systems_supported
        fail_msg: |
          CI system '{{ rs_ci_system }}' is not supported. Supported rs_ci_system values:
          {%- for item in rs_ci_systems_supported -%}
          "  - '{{ item }}'"
          {%- endfor -%}
      when:
        - rs_ci_system | default("") | length > 0
    - name: Validate junit2json variables are defined
      ansible.builtin.assert:
        that: "{{ condition }}"
        fail_msg:
          - "The condition {{ condition }} failed"
      loop:
        - 'junit2_input_reports_list | default([]) | length > 0'
        - 'junit2_output_dir | default("") | length > 0'
      loop_control:
        loop_var: condition
  tasks:
    - name: Convert JUnit reports convert to json without merging
      ansible.builtin.include_role:
        name: redhatci.ocp.junit2json
    - name: Detect metadata
      ansible.builtin.include_role:
        name: redhatci.ocp.report_metadata_gen
      vars:
        rmg_ci_system: "{{ rs_ci_system }}"
        rmg_ci_type: "{{ rs_ci_type }}"
        rmg_ci_url: "{{ rs_ci_url }}"
        rmg_ci_job_id: "{{ rs_ci_job_id }}"
        rmg_ci_build_id: "{{ rs_ci_build_id }}"
        rmg_ci_build_url: "{{ rs_ci_build_url }}"
        rmg_ci_build_number: "{{ rs_ci_build_number }}"
        rmg_
    - name: Combine tests and metadata
      ansible.builtin.include_role:
        name: redhatci.ocp.report_combine
    - name: Upload reports to Splunk
      ansible.builtin.include_role:
        name: redhatci.ocp.report_send
      vars:
        rs_report_path: "{{ global_json_reports_list[0] }}"
        rs_collector_target: "{{ splunk_channel }}"
      when:
        - global_json_reports_list | default([]) | length > 0
