---
- name: Deploy Container Runtime Configuration
  kubernetes.core.k8s:
    state: present
    src: "{{ manifests_folder }}/ContainerRuntime.yml"
  when: container_runtime_config is defined and container_runtime_config.changed
  notify:
    - wait for mcp update

- name: Deploy Cgroup Configuration
  kubernetes.core.k8s:
    state: present
    src: "{{ manifests_folder }}/CgroupConfiguration.yml"
  notify:
    - wait for mcp update

- name: Deploy Performance Profile
  kubernetes.core.k8s:
    state: present
    src: "{{ manifests_folder }}/PerformanceProfile.yml"
  notify:
    - wait for mcp update

- name: Force handlers to run immediately
  ansible.builtin.meta: flush_handlers
