---
# configure-nrop-operator.yml
# This playbook configures the NROP operator on the cluster.
# It sets the target pool, the scheduler image uri, and deploys the operator manifest.

# Variables required:
# kubeconfig: The kubeconfig to use.
# test_env: The environment to use.

# Variables optional:
# custom_scheduler: The custom scheduler to use.


- name: Configure NROP operator
  hosts: bastion
  gather_facts: false
  environment:
    K8S_AUTH_KUBECONFIG: "{{ kubeconfig }}"

  tasks:
    - name: Run role nrop_config
      ansible.builtin.include_role:
        name: nrop_config
