# workdir settings
tmp_workdir: "/tmp/wip"
manifest_dir: "{{ tmp_workdir }}/artifacts"

# scheduler settings
is_full_schedulable_cluster: false
scheduler_image_name: noderesourcetopology-scheduler
image_uri:
  prod: registry.redhat.io/openshift4
  stage: registry.stage.redhat.io/openshift4

# performance-profile settings
reserved_cpu_count: 4
rt_kernel: "true"
ppc_image: "registry.redhat.io/openshift4/ose-cluster-node-tuning-rhel9-operator:v4.21"
ppc_image_rhel8: "registry.redhat.io/openshift4/ose-cluster-node-tuning-operator:v4.12"

# sample device settings
device_plugin_image: "quay.io/k8stopologyawareschedwg/sample-device-plugin:v0.2.2"
