---
galaxy_info:
  role_name: container_image_mirror
  author: Telco Verification Team
  description: Mirror or remove container images from/to internal registries using skopeo
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - containers
    - skopeo
    - registry
    - mirror

dependencies: []
