---
- name: Get scheduler configuration
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: Scheduler
    name: cluster
  register: scheduler_info

- name: Set NROP target pool and base image
  ansible.builtin.set_fact:
    nrop_target_pool: "{{ 'master' if scheduler_info.resources[0].spec.mastersSchedulable | default(false) else 'worker' }}"
    base_image: "{% if ocp_version_minor == 12 %}rhel8{% else %}rhel9{% endif %}"

- name: Check if it's full schedulable cluster
  when: nrop_target_pool == 'master'
  block:
    - name: Get Nodes information
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Node
      register: nodes_info

    - name: Check if it's full schedulable cluster
      ansible.builtin.set_fact:
        is_full_schedulable_cluster: true
      when: nodes_info.resources | length >= 4

- name: Print target pool
  ansible.builtin.debug:
    msg: "Traget pool: {{ nrop_target_pool }}"

- name: Set scheduler image uri
  ansible.builtin.set_fact:
    scheduler_image_uri: "{{ image_uri[test_env] }}/{{ scheduler_image_name }}-{{ base_image }}:v{{ ocp_version_major }}.{{ ocp_version_minor }}"
  when: custom_scheduler is not defined

- name: Overwrite scheduler image uri
  ansible.builtin.set_fact:
    scheduler_image_uri: "{{ custom_scheduler }}"
  when: custom_scheduler is defined

- name: Print scheduler image uri
  ansible.builtin.debug:
    msg: "Scheduler image uri: {{ scheduler_image_uri }}"

- name: Deploy scheduler manifest
  ansible.builtin.include_tasks: deploy_manifest.yml
  vars:
    template_name: "templates/scheduler.yaml.j2"
    manifest_name: "operator-scheduler.yaml"
  when: deploy_performance_profile_only | bool is false

- name: Wait for MCP restart
  ansible.builtin.include_tasks: wait_for_mcp.yml
  when: (ocp_version_major ~ '.' ~ ocp_version_minor) is version('4.18', '<')
