---
- name: Generate Performance Profile using PPC container
  containers.podman.podman_container:
    name: ppc_tool
    image: "{{ nrop_ppc_image }}"
    rm: true
    entrypoint: performance-profile-creator
    detach: false
    authfile: "{{ tmp_must_gather_dir.path }}/pull_secret"
    volumes:
      - "{{ tmp_must_gather_dir.path }}:/must-gather:Z"
    command: >
      --mcp-name={{ target }}
      --reserved-cpu-count={{ reserved_cpu_count }}
      --rt-kernel={{ rt_kernel }}
      --must-gather-dir-path=/must-gather
      --power-consumption-mode=ultra-low-latency
  register: ppc_output

- name: Save generated profile to file
  ansible.builtin.copy:
    content: "{{ ppc_output.stdout }}"
    dest: "{{ tmp_must_gather_dir.path }}/performance-profile.yaml"
    mode: '0664'

- name: Read PerformanceProfile file
  ansible.builtin.slurp:
    src: "{{ tmp_must_gather_dir.path }}/performance-profile.yaml"
  register: profile_file

- name: Extract CPU settings
  ansible.builtin.set_fact:
    cpu_isolated: "{{ (profile_file.content | b64decode | from_yaml).spec.cpu.isolated }}"
    cpu_reserved: "{{ (profile_file.content | b64decode | from_yaml).spec.cpu.reserved }}"

- name: Deploy Performance Profile
  ansible.builtin.include_tasks: deploy_manifest.yml
  vars:
    template_name: "templates/performanceprofile.yaml.j2"
    manifest_name: "{{ target }}_performance-profile.yaml"
