- name: Deploy NTO configuration
  hosts: bastion
  gather_facts: false
  vars:
    kubeconfig: "/home/telcov10n/project/generated/hlxcl15/auth/kubeconfig" # TODO: for testing only should be removed
  environment:
    K8S_AUTH_KUBECONFIG: "{{ kubeconfig }}"

  tasks:
  - name: Ensure python packages are installed
    ansible.builtin.pip:
      name:
        - kubernetes >= 24.2.0
        - PyYAML >= 3.11

  - name: Retrieve worker nodes
    kubernetes.core.k8s_info:
      kind: Node
      label_selectors:
        - node-role.kubernetes.io/worker
    register: worker_nodes_info

  - name: Apply CNF label to all worker nodes
    kubernetes.core.k8s:
      definition:
        apiVersion: v1
        kind: Node
        metadata:
          name: "{{ item }}"
          labels:
            node-role.kubernetes.io/worker-cnf: ''
    loop: "{{ worker_nodes_info.resources | map(attribute='metadata.name') }}"

  - name: Apply MCP configuration
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', 'templates/machineConfigPool.yml.j2') }}"

  - name: Apply performance Profile 
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', 'templates/performanceProfile.yml.j2') }}"
    vars: 
        cpu_cores: "{{ worker_nodes_info.resources[0].status.capacity.cpu }}"


