---
- name: Get NROP pod information
  kubernetes.core.k8s_info:
    kind: Pod
    label_selectors:
      - app=numaresources-operator
  register: nrop_pods

- name: Set pod and namespace facts
  set_fact:
    pod_name: "{{ (nrop_pods.resources | selectattr('metadata.name', 'search', 'numaresources-controller-manager-') | first).metadata.name }}"
    operator_namespace: "{{ (nrop_pods.resources | selectattr('metadata.name', 'search', 'numaresources-controller-manager-') | first).metadata.namespace }}"
  when: nrop_pods.resources | length > 0

- name: Inspect features on deployed operator
  kubernetes.core.k8s_exec:
    namespace: "{{ operator_namespace }}"
    pod: "{{ pod_name }}"
    command: "bin/numaresources-operator --inspect-features"
  register: features_from_manager

- name: Set active features
  set_fact:
    active_features: "{{ (features_from_manager.stdout | from_json).active }}"

- name: Save active feature list
  ansible.builtin.copy:
    content: "{{ active_features }}"
    dest: "{{ tmp_workdir }}/artifacts/active_from_manager.json"
    mode: '0664'

- name: Get latest features list from tests image
  shell: |
    podman run {{ nrop_test_image_tag }} cat /usr/local/share/topics.json
  changed_when: latest_list.rc == 0
  register: latest_list

- name: Set latest features
  set_fact:
    latest_features: "{{ (latest_list.stdout | from_json).active  }}"

- name: Save active features from test image
  ansible.builtin.copy:
    content: "{{ latest_features }}"
    dest: "{{ tmp_workdir }}/artifacts/latest.json"
    mode: '0664'

- name: Features to skip
  set_fact:
    feature_to_skip: "{{ (latest_features | difference(active_features)) | join(' ') }}"

- name: Build the skip list (In latest but not in active, plus known bugs)
  set_fact:
    skip_filter: "!(feature: containsAny { {{ feature_to_skip }} })"
  when: feature_to_skip | length > 0

- name: Save Skip skip_filter
  ansible.builtin.copy:
    content: "{{ skip_filter | default('') }}"
    dest: "{{ tmp_workdir }}/artifacts/skip_filter.json"
    mode: '0664'

- name: Set Scope if Reboot
  ansible.builtin.set_fact:
    scope: "reboot"
  when: run_reboot_tests_only is true

- name: Set scope for Non-reboot tests
  ansible.builtin.set_fact:
    scope: "{{ topology_manager_scope }}"
  when: run_reboot_tests_only is false

- name: Create Test dir
  ansible.builtin.file:
    state: directory
    path: "{{ nrop_test_dir }}"
    mode: '0776'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Save test script
  ansible.builtin.template:
    src: nrop_test_script.j2
    dest: "{{ manifest_dir }}/{{ topology_manager_scope }}_nrop_test_script.sh"
    mode: '0776'
