---
- name: Configure hub OCP metrics collection
  ansible.builtin.set_fact:
    _collect_metrics_ocp_kubeconfig: "{{ collect_metrics_hub_kubeconfig }}"
    _collect_metrics_ocp_key_prefix: "hub_"
    _collect_metrics_ocp_scope: "hub "
    _collect_metrics_ocp_display_prefix: "Hub OCP"
    _collect_metrics_ocp_cluster_display_prefix: "Hub cluster"
    _collect_metrics_ocp_collect_worker_kernels: false

- name: Collect hub general OCP metrics
  ansible.builtin.include_tasks: _cluster_general_ocp.yml
