---
- name: Configure spoke OCP metrics collection
  ansible.builtin.set_fact:
    _collect_metrics_ocp_kubeconfig: "{{ collect_metrics_spoke_kubeconfig }}"
    _collect_metrics_ocp_key_prefix: "spoke_"
    _collect_metrics_ocp_scope: "spoke "
    _collect_metrics_ocp_display_prefix: "Spoke OCP"
    _collect_metrics_ocp_cluster_display_prefix: "Spoke cluster"
    _collect_metrics_ocp_collect_worker_kernels: true

- name: Collect spoke general OCP metrics
  ansible.builtin.include_tasks: _cluster_general_ocp.yml
